pipeline:
  agent:
    any:
  stages:
    - stage: "Log Jenkins Maven Docker Java and Git versions"
      steps:
        - sh "mvn -version"
        - sh "java -version"
        - sh "git --version"
    - stage: "Final Jenkins YAML Pipeline Stage"
      steps:
        - sh "echo 'Jenkins YAML Pipeline Complete'"
